version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build

  deploy:
    machine: true
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: |
                echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            - run: docker build -t jagadish11192/hackernews:$CIRCLE_BRANCH .

            # deploy the image
            - run: docker push jagadish11192/hackernews:$CIRCLE_BRANCH

            - run: eb deploy hello-world:latest --region=us-east-2 --application-name HackerNews
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy
